cmake_minimum_required(VERSION 3.20)

file(REMOVE_RECURSE "${WORK_ROOT}")
file(MAKE_DIRECTORY "${WORK_ROOT}/.git")
file(WRITE "${WORK_ROOT}/index.ts" "import './target';\n")
file(WRITE "${WORK_ROOT}/target.ts" "export const value = 1;\n")

foreach(configuration absent omitted disabled)
  if(configuration STREQUAL "omitted")
    file(WRITE "${WORK_ROOT}/.src-lintrc.toml" "version = 1\n")
  elseif(configuration STREQUAL "disabled")
    file(WRITE "${WORK_ROOT}/.src-lintrc.toml" "version = 1\n[cache]\nmax_mib = 0\n")
  endif()
  foreach(iteration RANGE 1 3)
    foreach(command check graph discover)
      execute_process(COMMAND "${CLI}" "${command}" "${WORK_ROOT}" --format json
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
      if(NOT result EQUAL 0)
        message(FATAL_ERROR "${configuration}: ${command} failed\n${output}\n${errors}")
      endif()
      if(EXISTS "${WORK_ROOT}/.src-lint")
        message(FATAL_ERROR "${configuration}: ${command} created a cache directory")
      endif()
    endforeach()
    file(APPEND "${WORK_ROOT}/index.ts" "\n")
  endforeach()
endforeach()
