cmake_minimum_required(VERSION 3.20)

function(check_selected command expected config)
  execute_process(
    COMMAND "${CLI}" "${command}" "${scope}" --config "${config}" --format json
    WORKING_DIRECTORY "${WORK_ROOT}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 10)
  if(NOT result EQUAL expected)
    message(FATAL_ERROR "${command} --config ${config}: expected ${expected}, got ${result}\n${output}\n${errors}")
  endif()
  if(expected EQUAL 1 AND NOT output MATCHES "orders")
    message(FATAL_ERROR "Selected policy was not reflected in ${command}: ${output}")
  endif()
  if(expected EQUAL 2 AND errors STREQUAL "")
    message(FATAL_ERROR "Config failure must report a diagnostic")
  endif()
endfunction()

file(REMOVE_RECURSE "${WORK_ROOT}")
file(MAKE_DIRECTORY "${WORK_ROOT}/domains/orders" "${WORK_ROOT}/domains/billing"
  "${WORK_ROOT}/empty")
file(WRITE "${WORK_ROOT}/domains/orders/main.ts" "import '../billing/private';\n")
file(WRITE "${WORK_ROOT}/domains/billing/private.ts" "export const value = 1;\n")
set(scope "domains/orders/main.ts")
set(json [[{"boundaries":{"orders":{"root":"domains/orders"},"billing":{"root":"domains/billing"}}}]])
set(toml "[boundaries.orders]\nroot = \"domains/orders\"\n[boundaries.billing]\nroot = \"domains/billing\"\n")
set(yaml "boundaries:\n  orders:\n    root: domains/orders\n  billing:\n    root: domains/billing\n")
file(WRITE "${WORK_ROOT}/.src-lintrc" "{}")
execute_process(COMMAND "${CLI}" check "${scope}" --format json
  WORKING_DIRECTORY "${WORK_ROOT}" RESULT_VARIABLE automatic_result OUTPUT_QUIET)
if(NOT automatic_result EQUAL 0)
  message(FATAL_ERROR "Automatic config should allow the unconfigured domains")
endif()

foreach(extension json toml yaml yml)
  set(content "${yaml}")
  if(extension STREQUAL "json")
    set(content "${json}")
  elseif(extension STREQUAL "toml")
    set(content "${toml}")
  endif()
  file(WRITE "${WORK_ROOT}/policy.${extension}" "${content}")
  foreach(command check discover graph)
    check_selected("${command}" 1 "policy.${extension}")
    check_selected("${command}" 1 "${WORK_ROOT}/policy.${extension}")
  endforeach()
endforeach()

file(WRITE "${WORK_ROOT}/package.json" "{\"name\":\"fixture\",\"src-lint\":${json}}")
string(REPLACE "[boundaries." "[tool.src-lint.boundaries." embedded_toml "${toml}")
file(WRITE "${WORK_ROOT}/pyproject.toml" "${embedded_toml}")
string(REPLACE "\n" "\n  " embedded_yaml "${yaml}")
foreach(name src-lint.yml src-lint.yaml)
  file(WRITE "${WORK_ROOT}/${name}" "src-lint:\n  ${embedded_yaml}")
endforeach()
foreach(name package.json pyproject.toml src-lint.yml src-lint.yaml)
  check_selected(check 1 "${name}")
endforeach()
set(scope .)
check_selected(check 1 policy.toml)
set(scope "domains/orders/main.ts")

file(WRITE "${WORK_ROOT}/domains/orders/.src-lintrc"
  [[{"boundaries":{"billing":{"public":["private.ts"]}}}]])
check_selected(check 0 policy.toml)
file(REMOVE "${WORK_ROOT}/domains/orders/.src-lintrc")
file(WRITE "${WORK_ROOT}/domains/billing/.src-lintrc"
  [[{"boundaries":{"billing":{"public":["private.ts"]}}}]])
check_selected(check 0 policy.toml)
file(WRITE "${WORK_ROOT}/domains/billing/.src-lintrc"
  [[{"boundaries":{"billing":{"public":[]}}}]])
check_selected(check 1 policy.toml)
file(REMOVE "${WORK_ROOT}/domains/billing/.src-lintrc")

file(WRITE "${WORK_ROOT}/.src-lintrc" "${json}")
check_selected(check 1 .src-lintrc)
file(WRITE "${WORK_ROOT}/bad.json" "{")
file(WRITE "${WORK_ROOT}/policy.txt" "${json}")
file(WRITE "${WORK_ROOT}/package.json" "{\"name\":\"no-policy\"}")
file(WRITE "${WORK_ROOT}/pyproject.toml" "[project]\nname = 'no-policy'\n")
file(WRITE "${WORK_ROOT}/src-lint.yaml" "name: no-policy\n")
execute_process(COMMAND mkfifo "${WORK_ROOT}/fifo.json" COMMAND_ERROR_IS_FATAL ANY)
file(CREATE_LINK "${WORK_ROOT}/missing.json" "${WORK_ROOT}/broken.json" SYMBOLIC)
set(scope empty)
foreach(config missing.json bad.json policy.txt package.json pyproject.toml src-lint.yaml
    empty fifo.json broken.json)
  foreach(command check discover graph)
    check_selected("${command}" 2 "${config}")
  endforeach()
endforeach()
