cmake_minimum_required(VERSION 3.20)

file(REMOVE_RECURSE "${WORK_ROOT}")
file(MAKE_DIRECTORY "${WORK_ROOT}/.git")
set(base "version = 1\n[cache]\nmax_mib = 1\n")
set(orders "[boundaries.orders]\nroot = \"services/orders\"\n")
set(billing "[boundaries.billing]\nroot = \"services/billing\"\npublic = [\"api/**\"]\n")
set(source "${WORK_ROOT}/services/orders/create.js")
set(target_config "${WORK_ROOT}/services/billing/.src-lintrc.toml")
file(WRITE "${WORK_ROOT}/.src-lintrc.toml" "${base}")
file(WRITE "${WORK_ROOT}/services/billing/api/index.js" "module.exports = 1;\n")
file(WRITE "${WORK_ROOT}/services/billing/proto/index.js" "module.exports = 1;\n")
file(WRITE "${WORK_ROOT}/services/billing/internal/ledger.js" "module.exports = 1;\n")

function(expect_result expected_exit rule)
  foreach(scope IN ITEMS "${source}" "${WORK_ROOT}")
    execute_process(COMMAND "${CLI}" check "${scope}" --format json ${ARGN}
      RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    if(NOT result STREQUAL "${expected_exit}")
      message(FATAL_ERROR "${CASE}: ${scope}: expected ${expected_exit}, got ${result}\n${output}\n${errors}")
    endif()
    if(expected_exit EQUAL 2)
      if(NOT errors MATCHES "configuration|multiple rc files")
        message(FATAL_ERROR "Expected configuration error\n${errors}")
      endif()
      continue()
    endif()
    string(JSON count LENGTH "${output}" findings)
    if(rule STREQUAL "")
      if(NOT count EQUAL 0)
        message(FATAL_ERROR "Unexpected findings\n${output}")
      endif()
      continue()
    endif()
    if(NOT count EQUAL 1)
      message(FATAL_ERROR "Expected one ${rule} finding\n${output}")
    endif()
    string(JSON actual_rule GET "${output}" findings 0 rule)
    if(NOT actual_rule STREQUAL rule)
      message(FATAL_ERROR "Expected ${rule}, got ${actual_rule}\n${output}")
    endif()
  endforeach()
endfunction()

function(expect_graph status rule)
  execute_process(COMMAND "${CLI}" graph "${source}" --format json
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
  if(result EQUAL 2)
    message(FATAL_ERROR "Graph failed\n${errors}")
  endif()
  string(JSON count LENGTH "${output}" edges)
  if(NOT count EQUAL 1)
    message(FATAL_ERROR "Expected one graph edge\n${output}")
  endif()
  string(JSON actual_status GET "${output}" edges 0 status)
  string(JSON actual_rule GET "${output}" edges 0 rule)
  if(NOT actual_status STREQUAL status OR NOT actual_rule STREQUAL rule)
    message(FATAL_ERROR "Unexpected graph classification\n${output}")
  endif()
endfunction()

if(CASE STREQUAL "template_expression")
  file(WRITE "${source}" [[const value = `${require("../billing/internal/ledger.js")}`;
]])
  expect_result(1 SL1001 --strict)
  expect_result(1 SL1001 --strict)
  expect_graph(violation SL1001)
  return()
endif()

if(CASE STREQUAL "source_allow")
  file(WRITE "${source}" "require(\"../billing/internal/ledger.js\");\n")
  file(WRITE "${WORK_ROOT}/.src-lintrc.toml"
    "${base}${orders}allow = [\"services/billing/internal/**\"]\n")
  expect_result(0 "" --strict)
  file(WRITE "${WORK_ROOT}/.src-lintrc.toml"
    "${base}${orders}allow = [\"services/billing/internal-old/**\"]\n")
  expect_result(1 SL1001 --strict)
  file(CREATE_LINK "../billing/internal" "${WORK_ROOT}/services/orders/alias" SYMBOLIC)
  file(WRITE "${source}" "require(\"./alias/ledger.js\");\n")
  file(WRITE "${WORK_ROOT}/.src-lintrc.toml"
    "${base}${orders}allow = [\"services/orders/alias/**\"]\n")
  expect_result(1 SL1001 --strict)
  return()
endif()

if(CASE STREQUAL "empty_directory")
  file(WRITE "${source}" "require(\"./empty\");\n")
  file(MAKE_DIRECTORY "${WORK_ROOT}/services/orders/empty")
  expect_result(0 SL2001)
  expect_result(1 SL2001 --strict)
  expect_graph(advisory SL2001)
  file(WRITE "${WORK_ROOT}/services/orders/empty/index.js" "module.exports = 1;\n")
  expect_result(0 "" --strict)
  return()
endif()

file(WRITE "${WORK_ROOT}/.src-lintrc.toml" "${base}${orders}${billing}")
file(WRITE "${source}" "require(\"../billing/api\");\n")
expect_result(0 "" --strict)
foreach(format toml json yaml)
  set(target_config "${WORK_ROOT}/services/billing/.src-lintrc.${format}")
  set(policy "[boundaries.billing]\npublic = []\n")
  if(format STREQUAL "json")
    set(policy [[{"boundaries":{"billing":{"public":[]}}}]])
  elseif(format STREQUAL "yaml")
    set(policy "boundaries:\n  billing:\n    public: []\n")
  endif()
  file(WRITE "${target_config}" "${policy}")
  expect_result(1 SL1001 --strict)
  expect_graph(violation SL1001)
  file(REMOVE "${target_config}")
endforeach()
set(target_config "${WORK_ROOT}/services/billing/.src-lintrc.toml")
file(CREATE_LINK "../billing/api" "${WORK_ROOT}/services/orders/alias" SYMBOLIC)
file(WRITE "${source}" "require(\"./alias\");\n")
file(WRITE "${target_config}" "[boundaries.billing]\npublic = []\n")
expect_result(1 SL1001 --strict)
expect_graph(violation SL1001)
file(WRITE "${source}" "require(\"../billing/proto\");\n")
file(WRITE "${target_config}" "[boundaries.billing]\npublic = [\"proto/**\"]\n")
expect_result(0 "" --strict)
file(WRITE "${target_config}" "[boundaries.billing]\npublic = []\n")
expect_result(1 SL1001 --strict)
file(WRITE "${WORK_ROOT}/.src-lintrc.toml"
  "${base}${orders}allow = [\"services/billing/proto/**\"]\n${billing}")
expect_result(0 "" --strict)
file(WRITE "${target_config}" "[boundaries.billing]\npublic = []\n"
  "[boundaries.orders]\nallow = [\"services/billing/proto/**\"]\n")
file(WRITE "${WORK_ROOT}/.src-lintrc.toml" "${base}${orders}${billing}")
expect_result(1 SL1001 --strict)
file(WRITE "${target_config}" "[boundaries.billing]\npublic = [\"*\"]\n")
expect_result(2 "" --strict)
file(WRITE "${source}"
  "require(\"./missing\"); require(\"../billing/proto\"); require(\"../billing/proto\");\n")
expect_result(2 "" --strict)

file(REMOVE "${source}")
set(source "${WORK_ROOT}/services/orders/create.go")
file(WRITE "${source}" "package orders\nimport \"example.com/repo/services/billing/api\"\n")
file(WRITE "${target_config}" "[boundaries.billing]\npublic = [\"api/**\"]\n")
file(WRITE "${WORK_ROOT}/services/billing/api/.src-lintrc.toml"
  "[boundaries.billing]\npublic = []\n")
expect_result(1 SL1001 --strict)
expect_graph(violation SL1001)
file(REMOVE "${WORK_ROOT}/services/billing/api/.src-lintrc.toml")
expect_result(0 "" --strict)
